---
# This playbook will install MariaDB and create db user and give permissions.

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - mariadb-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python

- name: upgrade all packages
  yum: name=* state=latest

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mariadb
  
- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775
  
- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes

- name: install firewalld 
  yum: name=firewalld state=present

- name: ensure that firewalld is started and enable at boot
  service: name=firewalld enabled=yes state=started

- name: insert firewalld rule
  become: yes
  become_method: sudo
  firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled immediate=yes zone=public
